### PR TITLE
Abstract out console log messages for iOS

### PR DESCRIPTION
**Pull request by mineshaftgap**
Apple does not like and has rejected apps, solely based on console
logging.  For the sake of not having to alter the code every time and
for beginners, I suggest that we make it only log if in debug mode.  I
have not done this for the Android version, but this would probably be
just a useful.

### CODE REVIEW

**Comment by brody2consult** [comment]
This is a good idea however I do not like every component adding its own version of the logging functions. I submitted a request to fix this problem in the core: https://issues.apache.org/jira/browse/CB-611

**Comment by mineshaftgap** [comment]
Thanks, makes sense.

**Comment by brody2consult** [comment]
I do not have much time this week, I will make the changes next weekend. My plan is to resolve the issue with the following:
- Add a macro like DLOG to SQLitePlugin.m to log the messages in debug mode only
- Use console.info() and console.error() in SQLitePlugin.js (iOS version only) to distinguish between info and error log messages
- Add documentation to README.md to document how to use console.setLevel() to control the level of logging (iOS version only).

@mineshaftgap thank you for raising the issue and the patch. I will make these changes myself next weekend, there is no need to do anything else on your side.. I have raised some issues to fix the logging on Cordova. I will keep this pull request open until I make these changes.

**Comment by mineshaftgap** [comment]
Sounds like a good plan.  Thanks for seeing the importance!

**Comment by brody2consult** [comment]
See https://issues.apache.org/jira/browse/CB-623 the Cordova project is now going to separate the logger functionality into a separate module. I would like to keep this issue at a lower priority until they have finished CB-623 in favor of some issues of functionality and bugs.

**Pull request closed without merging**
